name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.7', '3.0' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false

    - name: Install dependencies
      run: |
        # ensure bundler won't attempt deployment mode when Gemfile/Gemfile.lock differ
        bundle config --local deployment false || true
        bundle install --jobs 4 --retry 3

    - name: Run specs
      run: bundle exec rspec
